import { ProjectData } from "../typings";

export const projectData: ProjectData[] = [
  {
    id: "discord-demo",
    title: "Discord Clone with Chat Functionality",
    tags: ["Nextjs", "Typescript", "Tailwindcss", "Firebase", "ReduxToolkit"],
    image: "/discord_banner.jpeg",
    sourceCode: "",
    deployment: "",
  },
  {
    id: "liquidatooor",
    title: "Aave V3 dApp to liquidate loans",
    tags: [
      "Nextjs",
      "Typescript",
      "Solidity",
      "Tailwindcss",
      "Hardhat",
      "WAGMI",
      "AaveV3",
      "FlashLoans",
      "UniswapV3",
    ],
    image: "/aave_banner.jpg",
    sourceCode: "",
    deployment: "",
  },
  {
    id: "netflix-clone",
    title: "Netflix Clone",
    tags: ["Nextjs", "Typescript", "Tailwindcss", "Firebase", "Stripe"],
    image: "/netflix_banner.webp",
    sourceCode: "",
    deployment: "",
  },
  {
    id: "apple-clone",
    title: "Alternate Apple Clone",
    tags: ["Nextjs", "Tailwindcss", "Firebase", "Typescript", "Stripe"],
    image: "/apple_banner.png",
    sourceCode: "",
    deployment: "",
  },
  {
    id: "pokemon-nft-minter",
    title: "Pokémon NFT Minter",
    tags: [
      "Nextjs",
      "Javascript",
      "Solidity",
      "Hardhat",
      "Tailwindcss",
      "TheGraph",
    ],
    image: "/pokemon_banner.jpg",
    sourceCode: "",
    deployment: "",
  },
  {
    id: "reddit-clone",
    title: "Reddit Clone",
    tags: ["Nextjs", "Javascript", "Supabase", "SWR"],
    image: "/reddit_banner.jpg",
    sourceCode: "",
    deployment: "",
  },
  {
    id: "fintech-demo",
    title: "Fintech Startup Demo",
    tags: ["Nextjs", "Typescript", "Tailwindcss", "FramerMotion"],
    image: "/fintech_banner.png",
    sourceCode: "",
    deployment: "",
  },
  {
    id: "gamefi-demo",
    title: "GameFi Startup Demo",
    tags: ["Nextjs", "Typescript", "Tailwindcss", "FramerMotion"],
    image: "/gamefi_banner.png",
    sourceCode: "",
    deployment: "",
  },
  {
    id: "uniswap-clone",
    title: "Uniswap Clone",
    tags: [
      "Nextjs",
      "Javascript",
      "Solidity",
      "Hardhat",
      "Tailwindcss",
      "Sanity",
    ],
    image: "/uniswap_banner.avif",
    sourceCode: "",
    deployment: "",
  },
];
