import { ProjectData } from "../typings";

export const projectData: ProjectData[] = [
  {
    id: "discord-demo",
    title: "Discord Clone with Chat Functionality",
    tags: ["Nextjs", "Typescript", "Tailwindcss", "Firebase", "ReduxToolkit"],
    image: "/discord_banner.jpeg",
    description: "",
    sourceCode: "https://github.com/0xGuvnor/discord-demo",
    deployment: "https://discord-demo.vercel.app/",
  },
  {
    id: "liquidatooor",
    title: "Aave V3 dApp to liquidate loans",
    tags: [
      "Nextjs",
      "Typescript",
      "Solidity",
      "Tailwindcss",
      "Hardhat",
      "WAGMI",
      "AaveV3",
      "FlashLoans",
      "UniswapV3",
    ],
    image: "/aave_banner.jpg",
    description: `hello
              da
    world`,
    sourceCode: {
      frontend: "https://github.com/0xGuvnor/Liquidatooor_client",
      backend: "https://github.com/0xGuvnor/liquidatooor_hardhat",
    },
    deployment: "https://liquidatooor.vercel.app/",
  },
  {
    id: "netflix-clone",
    title: "Netflix Clone",
    tags: ["Nextjs", "Typescript", "Tailwindcss", "Firebase", "Stripe"],
    image: "/netflix_banner.webp",
    description: "",
    sourceCode: "https://github.com/0xGuvnor/netflix-clone",
    deployment: "https://neckfleeks.vercel.app/",
  },
  {
    id: "apple-clone",
    title: "Alternate Apple Clone",
    tags: ["Nextjs", "Tailwindcss", "Firebase", "Typescript", "Stripe"],
    image: "/apple_banner.png",
    description: "",
    sourceCode: "https://github.com/0xGuvnor/apple-alt-clone",
    deployment: "https://apple-alt-clone.vercel.app/",
  },
  {
    id: "pokemon-nft-minter",
    title: "Pokémon NFT Minter",
    tags: [
      "Nextjs",
      "Javascript",
      "Solidity",
      "Hardhat",
      "Tailwindcss",
      "TheGraph",
    ],
    image: "/pokemon_banner.jpg",
    description: "",
    sourceCode: {
      frontend: "https://github.com/0xGuvnor/nft-minter-pokemon-frontend",
      backend: "https://github.com/0xGuvnor/nft-minter-pokemon",
    },
    deployment: "https://mint-a-pokemon.vercel.app/",
  },
  {
    id: "reddit-clone",
    title: "Reddit Clone",
    tags: ["Nextjs", "Javascript", "Supabase", "SWR"],
    image: "/reddit_banner.jpg",
    description: "",
    sourceCode: "https://github.com/0xGuvnor/reddit-UI-clone",
    deployment: "https://reddit-ui-clone.vercel.app/",
  },
  {
    id: "fintech-demo",
    title: "Fintech Startup Demo",
    tags: ["Nextjs", "Typescript", "Tailwindcss", "FramerMotion"],
    image: "/fintech_banner.png",
    description: "",
    sourceCode: "https://github.com/0xGuvnor/fintech-demo",
    deployment: "https://fintech-demo.vercel.app/",
  },
  {
    id: "gamefi-demo",
    title: "GameFi Startup Demo",
    tags: ["Nextjs", "Typescript", "Tailwindcss", "FramerMotion"],
    image: "/gamefi_banner.png",
    description: "",
    sourceCode: "https://github.com/0xGuvnor/gamefi-demo",
    deployment: "https://metaverse-project-demo.vercel.app",
  },
  {
    id: "uniswap-clone",
    title: "Uniswap Clone",
    tags: [
      "Nextjs",
      "Javascript",
      "Solidity",
      "Hardhat",
      "Tailwindcss",
      "Sanity",
    ],
    image: "/uniswap_banner.avif",
    description: "",
    sourceCode: {
      frontend: "https://github.com/0xGuvnor/uniswap-demo-client",
      backend: "https://github.com/0xGuvnor/uniswap-demo-backend",
    },
    deployment: "https://uniswap-demo-client.vercel.app/",
  },
];
